import sys; sys.path.insert(0,'.')
from loom_ui import *
l=Loom()
try:
    l.login(); l.ir("/proyectos/"+PID)
    print("tcs:", cta(l, "Generar TCs", prefijo="07-fase2-casos-de-prueba"))
    l.ir("/proyectos/"+PID)
    print("arq:", cta(l, "Generar arquitectura", prefijo="08-fase2-arquitectura", esperar=1500))
    l.ir("/proyectos/"+PID)
    l.pg.locator("button").filter(has_text="Revisar en Diseño").first.click(); time.sleep(3)
    l.captura("09-arquitectura-generada-pendiente-de-aprobar")
    t=l.pg.inner_text("body"); i=t.find("Registro de «Arquitectura»"); print(t[i:i+700])
    l.pg.get_by_role("button", name="Ver documento").click(); time.sleep(3)
    l.captura("10-documento-de-arquitectura")
    l.pg.keyboard.press("Escape"); time.sleep(1)
    l.pg.get_by_role("button", name="Aprobar arquitectura").click(); time.sleep(4)
    l.captura("11-arquitectura-aprobada")
    l.ir("/proyectos/"+PID); l.captura("12-ruta-tras-aprobar-arquitectura")
finally: l.cerrar()
