import sys; sys.path.insert(0,'.')
from ciclo_ui import *
l=Loom()
try:
    l.login(); l.ir("/proyectos/"+PID)
    l.pg.get_by_role("tab", name=re.compile("Implementación")).click(); time.sleep(2)
    l.pg.locator("#gcp_sa").fill("loom-release-deployer@itz-inventario.iam.gserviceaccount.com")
    l.pg.locator("#gcp_wif").fill("projects/118746543308/locations/global/workloadIdentityPools/loom-github/providers/github")
    l.pg.locator("#gcp_wif").scroll_into_view_if_needed(); l.captura("37-fase4-configuracion-de-despliegue-service-account-y-wif")
    l.pg.get_by_role("button", name="Guardar cambios").click(); time.sleep(4)
    l.ir("/proyectos/"+PID); l.pg.get_by_role("tab", name=re.compile("Implementación")).click(); time.sleep(2)
    l.pg.get_by_role("button", name="Generar release.py").scroll_into_view_if_needed(); l.captura("37b-fase4-configuracion-guardada")
    l.pg.get_by_role("button", name="Generar release.py").click(); time.sleep(6)
    l.captura("37c-fase4-generar-release-py")
    esperar_actividad(l, maximo=300, cada=20, prefijo="37d-fase4-generar-release-progreso")
    l.pg.get_by_role("button", name=re.compile("Publicar en el repositorio")).click(); time.sleep(6)
    l.captura("38-fase4-publicar-pr-de-despliegue")
    esperar_actividad(l, maximo=600, cada=20, prefijo="38b-fase4-publicar-progreso")
    l.ir("/proyectos/"+PID); l.pg.get_by_role("tab", name=re.compile("Implementación")).click(); time.sleep(2)
    l.pg.get_by_role("button", name="Ejecutar release").scroll_into_view_if_needed(); l.captura("38c-fase4-pr-publicado")
finally: l.cerrar()
